### ISSUE TITLE
Request: Angular Support

### ISSUE THREAD

**Issue by bradmartin** [bradmartin/nativescript-lottie#10]

**Comment by justindujardin** [comment]
I might have some time, what needs to be done? A wrapper component? Has anyone run the demos from a clean git clone lately? I couldn't get any of them to run on iOS or Android. They just showed whitespace where the animation should be.

**Comment by bradmartin** [comment]
@rhanb - would be the one to ask how much is done here.

**Comment by rhanb** [comment]
@justindujardin , I have some issues with the properties which are fixed on my fork [here](https://github.com/rhanb/nativescript-lottie). I tested on Android and worked but not on iOS, and I have some issues to sync assets to the platform/android/src/main/assets folder even after following the README instructions, so hard to test.. 
I'm currently working on a hook to allow syncing assets from the `app` folder which you can find [here](https://github.com/rhanb/nativescript-dev-assets), but doesn't work yet.
