### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by votiakov** [bradmartin/nativescript-lottie#2]
Hello, Brad!

I found this awesome lib by airbnb and decided to write a plugin for NS. That's awesome that you have already done this) I offer you an extra pair of hands to work on this awesome plugin. Just wanted to ask if you already started the iOS implementation so I can pull the most fresh code.

**Comment by bradmartin** [comment]
Hey @votiakov - thanks for offering and I'm sure there might be some things that need improved and added. Published 1.1.0 with basic iOS support last night. Everything should be merged that I'm aware of. One thing I'd like to see added is `propertyChange` events for the properties: src, loop, autoPlay so an instance can be re used. Plus the cache strategy, not sure if this is on iOS or not but I didn't wire it up for Android all the way. I'll open separate issues with these items and if you want to help just ping the issue, if not, no worries 😄

**Comment by votiakov** [comment]
Oh man you are fast 👍  
I should pay more attention to the latest commits :smile:
I will see what I can do
