### ISSUE TITLE
nativescript-dev-assets conflicts with NativeScript 4.0 project layout

### ISSUE THREAD

**Issue by lambourn** [bradmartin/nativescript-lottie#21]
Dev devDependency `nativescript-dev-assets` is not needed for a NativeScript 4.0 project structure. Actually, it makes the build break.

Starting with NS 4.0, we can have a real Android project structure below App_Resources/Android (https://github.com/NativeScript/nativescript-cli/pull/3347). After running `tns resources update` there is an `assets` folder in which lottie animations can be placed.

However, using nativescript-lottie will install nativescript-dev-assets which does not work with the new layout.

We worked around it by forcibly removing the prepare hook of nativescript-dev-assets prior building.

Could you please create a NS 4.0 compatible version of nativescript-lottie which does not have the nativescript-dev-assets devDependency?

**Comment by bradmartin** [comment]
2.0.0 should resolve this. Let me know if any issues come up.
