### ISSUE TITLE
Cannot read property 'CacheStrategy' of undefined

### ISSUE THREAD

**Issue by alereisan** [bradmartin/nativescript-lottie#22]
After installing the plugin and setting up a basic example (like described in Readme), when I try to run the app, I get the error:

> JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'CacheStrategy' of undefined
JS: TypeError: Cannot read property 'CacheStrategy' of undefined
JS:     at exports.CacheStrategy.exports.CacheStrategy (file:///data/data/ch.inaffect.yoojis.kies/files/app/tns_modules/nativescript-lottie/nativescript-lottie.js:151:80)
JS:     at Object.<anonymous> (file:///data/data/ch.inaffect.yoojis.kies/files/app/tns_modules/nativescript-lottie/nativescript-lottie.js:154:3)
JS:     at require (<anonymous>:1:266)
JS:     at Object.<anonymous> (file:///data/data/ch.inaffect.yoojis.kies/files/app/cars/car-list.component.js:5:29)
JS:     at require (<anonymous>:1:266)
JS:     at Object.<anonymous> (file:///data/data/ch.inaffect.yoojis.kies/files/app/cars/cars.module.js:12:28)
JS:     at require (<anonymous>:1:266)
JS:     at file:///data/data/ch.inaffect.yoojis.kies/files/app/tns_modules/tns-core-modules/globals/globals.js:92:32
JS:     at new ZoneAwarePromise (file:///data/data/ch.inaffect.yoojis.kies/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:777:29)
JS:     at Object.import (file:///data/data/ch.inaffect.yoojis.kies/files/app/tns_modules/tns-core-modules/globals/globals.js:90:16)
JS:     at SystemJsNgModuleLoader.loadAndCompile (file:///data/data/ch.inaffect.yoojis.kies/files/app/tns_modules/@angular/core/bundles/core.umd.js:6608:29)
JS:     at SystemJsNgModuleLoader.load (file:///data/data/ch.inaffect.yoojis.kies/files/app/tns_modules/@angular/core/bundles/core.umd.js:6592:60)
JS:     at RouterConfigLoader.loadModuleFactory (file:///data/data/ch.inaffect.yoojis.kies/files/app/tns_modules/@angular/router/bundles/router.umd.js:4617:72)
JS:     at RouterConfigLoader.load (file:///data/data/ch.inaffect.yoojis.kies/files/app/tns_modules/@angular/router/bundles/router.umd.js:4597:52)
JS:     at MergeMapSubscriber.project (file:///data/data/ch.inaffect.yoojis.kies/files/app/tns_modules/@angular/router/bundles/router.umd.js:2083:74)
13:11:37 - Starting compilation in watch mode...

I am using nativescript-angular

**Comment by ianrothmann** [comment]
I had the same problem but it was fixed after a platform remove/platform add.
