### ISSUE TITLE
Inconsistent behaviour across iPhone models and Android

### ISSUE THREAD

**Issue by hiperbou** [bradmartin/nativescript-lottie#24]
I'm using NativeScript 3x and It seems impossible to get consistent results with this library.
I've made a small example to ilustrate it.

> <Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:Lottie="nativescript-lottie">
    <StackLayout  backgroundColor="lightgray">
        <Lottie:LottieView src="A.json"  loop="true" autoPlay="true"/>
    </StackLayout>
</Page>

And this is the result:

![lottie](https://user-images.githubusercontent.com/12442874/41114656-564831ec-6a85-11e8-9729-ff6f76d563f7.png)

I ended up with diferent layouts for Android an iOS, and tweaking css properties for each iPhone family.
Trying to get a simple full screen animation working in every device is frustrating and time consuming with a lot of trial and error to tweak values.

**Comment by rhanb** [comment]
@hiperbou , do you manage to have a consistent result on Android devices at least?The Lottie  Android and iOS APIs are quite different and the iOS one was a bit tricky to integrate with NativeScript. Could provide more code and different options that you tried?  Thanks

**Comment by hiperbou** [comment]
I had no problems in android, We tested in different real devices without noticeable differences.
Here there is another test using more layouts.

> <Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:Lottie="nativescript-lottie" backgroundSpanUnderStatusBar="true" actionBarHidden="true">
    <StackLayout width = "100%" height = "100%"  backgroundColor="lightgray"  >
        <StackLayout marginBottom="10" height = "65%"  backgroundColor="lightgreen">
                <Lottie:LottieView id="onboardingAnim" src="A.json" loop="true" autoPlay="true" height="60%" width="80%"  horizontalAlignment="center" marginTop="10"  backgroundColor="blue"/>
        </StackLayout>
    </StackLayout>
</Page>

And the results:
![android2](https://user-images.githubusercontent.com/12442874/41159596-56429ca2-6b2d-11e8-90a4-f4a3068d18f4.png)
![iphonex](https://user-images.githubusercontent.com/12442874/41159595-56278cc8-6b2d-11e8-80e9-94fdbe2a0fbc.png)
![iphone5s](https://user-images.githubusercontent.com/12442874/41159597-565c30ae-6b2d-11e8-8286-a93c9069985c.png)
In the next one, the animation is slightly down past its container, it's not noticeable in the screenshot, check the shadow, because it could look similar as iPhone X result, but it isn't.
![iphone6p](https://user-images.githubusercontent.com/12442874/41159598-56779736-6b2d-11e8-9f6b-13c347f8c1d3.png)
![iphone6s](https://user-images.githubusercontent.com/12442874/41159600-56945042-6b2d-11e8-9ca9-976dce29bc75.png)

**Comment by rhanb** [comment]
That's what I thought, as I told you the iOS API is a bit tricky and the implementation is not as easy as for Android. Thanks for the examples, it will help us to fix the issue 👍

**Comment by rhanb** [comment]
@hiperbou should be fixed with the latest version thanks to @hamdiwanis PR

**Comment by hiperbou** [comment]
I supose these changes aren't available for the NativeScript 3x version of the library. I'll need to update to Nativescript 4, am I right?

**Comment by rhanb** [comment]
@hiperbou yep you're right, you'll need to upgrade to v4, the fix for this issue actually uses APi that exists since `4.0`
