### ISSUE TITLE
How to use theme?

### ISSUE THREAD

**Issue by mudlabs** [bradmartin/nativescript-lottie#41]
Could someone build a simple [Playground](https://play.nativescript.org/) example of how to use `theme`, I don't get it?

**Comment by bradmartin** [comment]
@mudlabs - Playground doesn't work with external native dependencies which Lottie is. You could make a repo with the plugin and if you need help use it for trial/error/help.

`theme` will likely be deprecated in the next release in a couple of days. The latest PR overhauls the plugin to match the native counterparts 👍

**Comment by mudlabs** [comment]
Ok, I'll wait for the release then. Thanks.
