### ISSUE TITLE
Can't run app for iOS

### ISSUE THREAD

**Issue by jlooper** [bradmartin/nativescript-lottie#5]
I can't run my own integration of Lottie for iOS, and since can reproduce the error I get on my own work when I run the demo app, I figure there's something wrong:

```
1   0x1059ad7cb NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x1060821ee ffi_closure_unix64_inner
3   0x106082b22 ffi_closure_unix64
4   0x106db2e70 -[UIViewController view]
5   0x106c7c4b5 -[UIWindow addRootViewControllerViewIfPossible]
6   0x106c7cc06 -[UIWindow _setHidden:forced:]
7   0x106c90519 -[UIWindow makeKeyAndVisible]
8   0x10608297d ffi_call_unix64
9   0x121917cd0
file:///app/tns_modules/tns-core-modules/ui/builder/builder.js:175:56: JS ERROR Error: Building UI from XML. @file:///app/main-page.xml:12:17
	 > Can't find variable: LAAnimationView
Feb 12 17:05:50 LOOPERMAC com.apple.CoreSimulator.SimDevice.1552CC18-C70B-4209-9F17-D04A886CD04C.launchd_sim[76258] (UIKitApplication:org.nativescript.demo[0xdba5][76815]): Service exited due to Segmentation fault: 11
```

**Comment by bradmartin** [comment]
If you cloned the repo to run the demo you have to make sure you transpile
the TS to js that's likely why it's not working for you.

**Comment by bradmartin** [comment]
Just realized who this was :) didn't even check lol let me know Jen if it
works or not

**Comment by jlooper** [comment]
hi, I have it running on Android but iOS is not happy. I'm wondering if there have been recent changes in the Lottie pod; there seem to be issues cropping up on that repo: https://github.com/airbnb/lottie-ios/issues/75 (cc @NathanWalker) thanks!

**Comment by NathanWalker** [comment]
@jlooper I just ran the demo just fine. The latest Pod that is installed is `1.0.0` of `lottie-ios` which is correct.

I just pushed up a small tweak to the demo run command. Ever since the 2.5.0 {N} release, I have been using `tns run ios --emulator` instead of `tns emulate ios` since I read the emulate command was being deprecated or removed, not sure if related but make sure you're using the run command.

All works here after a complete clear of everything in this plugin and fresh setup.

This error:
```
Can't find variable: LAAnimationView
```
...is directly indicative of the Pod not getting installed. When you run `tns run ios --emulator`, make sure you see the pod being installed in the output - Also double-check that `nativescript-lottie` is in your project's `package.json` `dependencies` section; if it's not, no Cocoapod would ever be installed.

**Comment by jlooper** [comment]
hi, Nathan, the pod is definitely installed. 

```
Installing pods...
Analyzing dependencies
Downloading dependencies
Installing lottie-ios (1.0.2)
Generating Pods project
Integrating client project
Integrating client project

[!] Please close any current Xcode sessions and use `demo.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
Project successfully prepared (ios)
```
Everything builds ok, then fails with the LAAnimationView issue. I've been using `tns run ios` or `tns run ios --clean` as needed, seems to do the job. I'm just wondering if there's some dependency/installation that I don't have on this machine, e.g. Carthage? https://github.com/airbnb/lottie-ios/issues/75

**Comment by NathanWalker** [comment]
Is this on a repo you could share? would be curious to run. I don't have Carthage and have never installed anything specific related to Cocoapods or anything special with XCode - standard and typical setup here.

**Comment by jlooper** [comment]
thanks Nathan...it's here https://github.com/jlooper/heart - much appreciated!!

**Comment by NathanWalker** [comment]
Ran on first try here - just cloned and ran: `tns run ios --emulator`
Strange you would have an issue - I'll ping ya' on Slack for further... gonna close this as it appears to be particular to something on your setup.

**Comment by Arcrueid** [comment]
Same error but i just change 
this._ios = LAAnimationView.animationNamed(this._src);
to 
this._ios = LOTAnimationView.animationNamed(this._src);

in nativescript-lottie.ios.js file and now works!

**Comment by jlooper** [comment]
@arcrueid how did you figure out this change? Is it something that should be PR'd?

**Comment by Arcrueid** [comment]
I just read the framework and the object name is LOTAnimationView not LAAnimationView xD

**Comment by NathanWalker** [comment]
I've never had an issue so curious with this - I wonder if my local Cocoapods have v1 of the pod cached but maybe there is a point update out there with a rename that your side is pulling?
Checking repository now...

**Comment by Arcrueid** [comment]
Oh yeah... Trying to make it work i update pod repository!

PD: sry for my english

**Comment by jlooper** [comment]
I did have to do a pod update to even get it to install, I wonder if there has been a change to the pod and thus this incompatibility

**Comment by NathanWalker** [comment]
Wow yep just 5 days ago a rename!
https://github.com/airbnb/lottie-ios/commit/1454d810350a4b89ccef9cf9c9e18d1b2ad447e3

Ok so when I developed the iOS side, my local cocoapods installed the version before the rename and subsequently would always reuse the cached spec.
Good to know - thanks for heads up, would you like to submit a PR?
We can then bump and publish this here.

**Comment by jlooper** [comment]
I'M NOT GOING CRAZY! LOOOL ok thanks!
