### ISSUE TITLE
Nativescript 6.2 not build

### ISSUE THREAD

**Issue by bazookon** [bradmartin/nativescript-lottie#51]
I put my json animation files into App_Resources/assets/  but faild

> Execution failed for task ':app:mergeDebugResources'.
> /**/platforms/android/app/src/main/res/assets/success.json: Error: The file name must end with .xml

**Comment by bradmartin** [comment]
See the demo for correct file location to put your native `assets` for android/ios projects.

https://github.com/bradmartin/nativescript-lottie/tree/master/demo/app/App_Resources/Android/src/main/assets
