### ISSUE TITLE
NativeScript 7 Support

### ISSUE THREAD

**Issue by AgentEnder** [bradmartin/nativescript-lottie#63]

**Comment by mattkenefick** [comment]
+1 

Any ideas/timeline on NS 7 support? Going through this right now.

**Comment by bradmartin** [comment]
Will try to get a release out today or tomorrow to handle this for now, the plugin eventually will move to a scoped version but I'll get a release out under this npm package to provide support before it is deprecated.

**Comment by mattkenefick** [comment]
Looking forward to it. Thanks a lot @bradmartin

**Comment by bradmartin** [comment]
Version 5.0.1 of `nativescript-lottie` should now be working with NS7+ - let me know of any issues @mattkenefick

**Comment by mattkenefick** [comment]
Running into an issue with filepath. _Note:_ This setup **did** work previously and the file locations didn't change.

First, the trace:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: java.io.IOException: No such file or directory
System.err:
System.err: StackTrace:
System.err: ensureFile(file: app\packages\core\file-system\file-system-access.android.ts:477:24)
System.err:     at getFile(file: app\packages\core\file-system\file-system-access.android.ts:45:14)
System.err:     at fromPath(file: app\packages\core\file-system\index.ts:179:35)
System.err:     at loadLottieJSON(file: node_modules\nativescript-lottie\lottie.android.js:16:26)
System.err:     at setSrc(file: node_modules\nativescript-lottie\lottie.android.js:115:12)
System.err:     at [src:setNative](file: node_modules\nativescript-lottie\lottie.android.js:124:13)
...
```

I've tried a variety of `App_Resources/...` paths with my JSON files:

```
App_Resources/Android/src/main/assets/json/my-file.json

App_Resources/Android/json/my-file.json
App_Resources/Android/assets/json/my-file.json
App_Resources/Android/src/json/my-file.json
App_Resources/Android/src/assets/json/my-file.json
App_Resources/Android/src/main/json/my-file.json
App_Resources/Android/src/main/assets/json/my-file.json
```

None of which worked.

I tried tinkering with the code in `lottie.android.js`, line 10: loadLottieJSON. I changed the path it looks and where I put them, and it seemed to work.

```
// lottie.android.js

function loadLottieJSON(iconSrc) {
    if (!cache.has(iconSrc)) {
        const file = File.fromPath(appPath + '/assets/' + iconSrc);
        // const file = File.fromPath(iconSrc);

        return file.readText().then(r => {
            cache.set(iconSrc, r);
            return r;
        });
    }
    return Promise.resolve(cache.get(iconSrc));
}
```

and moved my JSON files to `/my-project/app/assets/json/my-file.json` which ends up existing as:

```
{
JS:   "_path": "/data/data/com.company.project/files/app/assets/json/my-file.json",
JS:   "_name": "my-file.json",
JS:   "_extension": ".json"
JS: 
}
```

I'm not sure if this is a good solution going forward or if I'm overlooking something. Perhaps I should've been cleaning/wiping/resetting something? 

@bradmartin Thoughts?

**Comment by bradmartin** [comment]
You updated the project, so you have a new webpack.config. Go look for the `globs` and add the directory or all `.json` files to be bundled in your project 👍  that should be it. I think there is a note on the README about it. 

Perhaps the plugin should say something if the file isn't found and log a warning to the console??? Thoughts?? Would you be willing to make a PR to do that?

Prob instead of crashing the app when the file can't be read, we just wrap it in a `try/catch` and console.log('File not found be sure your lottie json files are bundled... some webpack mention, maybe a URL linking them to the webpack config glob section...). Then still throw the error or not... not sure what is best? I hate crashing the apps because of this so maybe a warning is better 🤔

**Comment by bradmartin** [comment]
ahhh I misread some of your post. so @mattkenefick  - if the files are in app_Resources, just try using `Filename.json` as the lottie `src` and see if that works.

I think we need to make the loading more robust and handle the different file locations. If you'd like to help with that, would be awesome. I have other plugins I need to get updated for now so will be a bit before I can circle back.

**Comment by mattkenefick** [comment]
@bradmartin Running a bit short on time at the moment, but as per your last comment, I did try putting my `my-file.json` in every single folder from app -> App_Resources -> etc and referencing it by `src="my-file.json"` without success. (if that's what you were referring to)

**Comment by mattkenefick** [comment]
If I do a `src="/my-file.json"` I get:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: java.io.IOException: Read-only file system
System.err:
System.err: StackTrace:
System.err: ensureFile(file: app\packages\core\file-system\file-system-access.android.ts:477:24)
System.err:     at getFile(file: app\packages\core\file-system\file-system-access.android.ts:45:14)
System.err:     at fromPath(file: app\packages\core\file-system\index.ts:179:35)
System.err:     at loadLottieJSON(file: node_modules\nativescript-lottie\lottie.android.js:12:26)
System.err:     at setSrc(file: node_modules\nativescript-lottie\lottie.android.js:108:12)
```

If I do it without a preceding slash, I get a slightly different but similar error:  `src="my-file.json"`


```System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: TypeError: Cannot read property 'mkdirs' of null
System.err:
System.err: StackTrace:
System.err: ensureFile(file: app\packages\core\file-system\file-system-access.android.ts:476:30)
System.err:     at getFile(file: app\packages\core\file-system\file-system-access.android.ts:45:14)
System.err:     at fromPath(file: app\packages\core\file-system\index.ts:179:35)
System.err:     at loadLottieJSON(file: node_modules\nativescript-lottie\lottie.android.js:12:26)
System.err:     at setSrc(file: node_modules\nativescript-lottie\lottie.android.js:108:12)
System.err:     at [src:setNative](file: node_modules\nativescript-lottie\lottie.android.js:117:13)
System.err:     at applyAllNativeSetters(file: app\packages\core\ui\core\properties\index.ts:1359:19)```


And again, this has the `my-file.json` polluted all throughout the project and App_Resources.

**Comment by mattkenefick** [comment]
I can try to put something together if this looks like a bug and not my own negligence

**Comment by bradmartin** [comment]
So the demo I have:
https://github.com/bradmartin/nativescript-lottie/blob/master/demo/app/main-view-model.ts#L12
 pointing to json files in app_resources and it's working.

I think you originally had yours there.

Could you run `ns clean` in your project then `ns run android` on the device/emulator and see what happens. Maybe remove all the local assets you were copying to diff directories before the clean as well. @mattkenefick

**Comment by mattkenefick** [comment]
I'll investigate further and see what i find; starting with your demo. Can report back tomorrow

**Comment by mattkenefick** [comment]
@bradmartin I found the issue; it was not prefixing with `res://` 

There is/was a demo where it used a relative path like:

```      <LottieView src="AndroidWave.json"  loop="true" autoPlay="true" backgroundColor="red" horizontalAlignment="center"></LottieView>
```

which worked previously. My code followed that example assuming it would start within the App_Resources folder somewhere. By making my code look like:

```
                <LottieView
                    class="animation-success"
                    src="res://json/answer-correct-04.json"
                    height="30"
                    width="30"
                    left="10"></LottieView>
```

... that did the trick.
