### ISSUE TITLE
iOS 14 renders but doesn't display

### ISSUE THREAD

**Issue by cbun097** [bradmartin/nativescript-lottie#68]
The plugin works renders well with any Android devices, on iOS is rendered but it doesn't not display. I tried with iOS emulator ios 12,13 and 14 (iPhone and iPAd) and also giving width and height.

Repo: https://github.com/cbun097/nativescript

Angular: 10
NativeScript: 7

Thanks!

**Comment by wendt88** [comment]
+1

**Comment by bradmartin** [comment]
Can you try calling `playAnimation()` on your lottieview instance and see if that kicks it off?

**Comment by wendt88** [comment]
for me `playAnimation()` does not kicks it off, but nothing happens and `completionBlock` never gets called

**Comment by apsaros** [comment]
Same issue here, running on Vue.
Tried with various setups such as autoplay or, like the example below, playAnimation() in the loaded method:

```
lottieLoaded(args) {
      console.log("lottie loaded", args.object);
      args.object.playAnimation();
      console.log("lottie animating", args.object.isAnimating());
    },

CONSOLE LOG: lottie loaded LottieView(6)
CONSOLE LOG: lottie animating false
```

**Comment by fpaaske** [comment]
I have the same issue too. I'm using Angular 8.2.0, NS 6.5.24 and plugin version 4.0.1.
It's not rendering on iOS 12.4, 13.5, 14.5.

```
<StackLayout>
    <LottieView [src]="src"
                [loop]="loop"
                [autoPlay]="autoPlay"
                (loaded)="lottieViewLoaded($event)"></LottieView>
</StackLayout>
```

    lottieViewLoaded(event) {
        console.log("lottieViewLoaded: ", event.object); // prints 'lottieViewLoaded ProxyViewContainer(8)'
        //this.lottieView = <LottieView>event.object;
        //this.lottieView.playAnimation(); // fails with playAnimation is undefined
    }

**Comment by apsaros** [comment]
Have someone found a solution to this? Any news @bradmartin ?

**Comment by mcalc001** [comment]
+ 1

**Comment by mcalc001** [comment]
Looked like its a timing issue - 

```
lottieLoaded(args) {
      setTimeout(()=>{
          args.object.playAnimation();
       }, 500 }
    }
```
will work .

**Comment by apsaros** [comment]
Great with some workaround @mcalc001, I managed to fix it at my end without the timeout though. 

Embarrassing enough, I missed that you had to update the src reference on your LottieViews with res://
If it helps anyone else, the lottie files (json) still resides under App_Resources/iOS, however don't forget to add **res://** like so:

`src="res://my-lottie-file.json"`

**Comment by bradmartin** [comment]
I've gone ahead and published  `5.0.3` with a simple timeout `(0)` around the `playAnimation` method which seems to fix the demo apps on iOS 14. Hopefully others can confirm this fixes their apps. It's not perfect but it seems to help in some scenarios.

**Comment by wendt88** [comment]
for me it does not solved the problem

**Comment by bradmartin** [comment]
@wendt88 can you open a new issue with the full extent of your code (package.json, relevant usage of lottie as well)?
