### ISSUE TITLE
plugin not working with nativescript 3.0.0 over android device

### ISSUE THREAD

**Issue by Nestorferrando** [bradmartin/nativescript-lottie#7]
Hi! I tried this plugin with nativescript 3.0.0 and it doesn't seem to work. No error message, just the 'lottie views' don't appear on the layout

I did the workaround of copying the animation jsons directly to the asset folder on android.

I made the same steps with a project based on nativescript 2.5.0 and worked perfectly.

**Comment by bradmartin** [comment]
Thanks for reporting. This will need to be migrated for the breaking changes in view components for NS 3+. If you have time for a PR that would be great :)

**Comment by Nestorferrando** [comment]
Hi! I've working on this. I though that just moving the code from _createUI() to createNativeView() was enough to make it work again.  I tried it but it didn't work, some weird java native errors appear and nothing renders. Sadly, my knowledge on nativescript/javascript is quite low and I don't know what to do now.

These are the errors that appear at the console:


05-18 14:31:35.153  9040  9040 F art     : art/runtime/java_vm_ext.cc:470]     from java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[])
05-18 14:31:35.153  9040  9040 F art     : art/runtime/java_vm_ext.cc:470]   at com.tns.Runtime.callJSMethodNative(Native method)
...

**Comment by bradmartin** [comment]
Understand - there is a learning curve with the inner workings 😄 but once you learn it you become unstoppable 👍 . So here is the first doc on migrating https://github.com/NativeScript/NativeScript/wiki/Migrating-Plugins-to-NativeScript-3.0 and in that doc is a link to the breaking changes: https://github.com/NativeScript/NativeScript/blob/master/Modules30Changes.md so you are on the right track. You'll probably be most interested in [this section](https://github.com/NativeScript/NativeScript/blob/master/Modules30Changes.md#property-system) on the Property and View changes. Hope this helps get you moving again.

**Comment by bradmartin** [comment]
1.2.0 published with NS 3x support
